// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }




import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata:Metadata = {
  title: "Mallumeet - Talk with Strangers Online",
  description:
    "Mallumeet is a free online chat platform to meet and talk with strangers securely. Start chatting instantly without signup.",
  keywords: [
    "chat with strangers",
    "online chat",
    "video call strangers",
    "Mallumeet",
    "Omegle alternative",
    "free chat app"
  ],
  openGraph: {
    title: "Mallumeet - Talk with Strangers Online",
    description:
      "Mallumeet lets you chat and video call with strangers instantly. 100% free and secure.",
    url: "https://mallumeet.netlify.app",
    siteName: "Mallumeet",
    images: [
      {
        url: "https://mallumeet.netlify.app/og-image.jpg", // Replace with actual image
        width: 1200,
        height: 630,
        alt: "Mallumeet Chat with Strangers",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Mallumeet - Talk with Strangers Online",
    description:
      "Mallumeet is a free online chat platform to meet and talk with strangers instantly.",
    images: ["https://mallumeet.netlify.app/og-image.jpg"], // Replace with actual image
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full bg-gray-100`}>
        <main className="h-full">
          {children}
        </main>
      </body>
    </html>
  )
}